import type { BookingRecord, BookingStatus } from "@/features/appointments/types";
import { addNotification } from "@/features/notifications/storage";
const STORAGE_KEY = "schedula-bookings";
export function getBookings(): BookingRecord[] { if (typeof window === "undefined") return []; try { const stored = window.localStorage.getItem(STORAGE_KEY); return stored ? JSON.parse(stored) as BookingRecord[] : []; } catch { return []; } }
function write(items: BookingRecord[]) { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); window.dispatchEvent(new Event("schedula-bookings-changed")); }
export function saveBooking(booking: BookingRecord): void { write([booking, ...getBookings()]); addNotification({ audience:"user", title:"Appointment booked", message:`${booking.doctorName} · ${booking.date} at ${booking.time}`, appointmentId:booking.id }); }
export function updateBooking(id: string, patch: Partial<BookingRecord>): BookingRecord | null { let updated: BookingRecord | null = null; const items=getBookings().map(b=>{ if(b.id!==id)return b; updated={...b,...patch,updatedAt:new Date().toISOString()}; return updated; }); write(items); return updated; }
export function updateBookingStatus(id: string, status: BookingStatus): void { const before=getBookings().find(b=>b.id===id); const updated=updateBooking(id,{status}); if(!updated)return; const titleMap:Record<BookingStatus,string>={pending:"Appointment pending",confirmed:"Appointment confirmed",upcoming:"Upcoming appointment",completed:"Appointment completed",cancelled:"Appointment cancelled",missed:"Appointment missed"}; addNotification({audience:"user",title:titleMap[status],message:`${updated.doctorName} · ${updated.date} at ${updated.time}`,appointmentId:id}); if(status==="confirmed") addNotification({audience:"doctor",doctorId:updated.doctorId,title:"Appointment confirmed",message:`${updated.patientName||"Patient"} is confirmed for ${updated.date} ${updated.time}`,appointmentId:id}); if(before&&before.status!==status) window.dispatchEvent(new Event("schedula-bookings-changed")); }
export function rescheduleBooking(id:string,date:string,time:string){const updated=updateBooking(id,{date,time,status:"confirmed"});if(updated){addNotification({audience:"user",title:"Appointment rescheduled",message:`New time: ${date} at ${time}`,appointmentId:id});addNotification({audience:"doctor",doctorId:updated.doctorId,title:"Appointment rescheduled",message:`${updated.patientName||"Patient"} moved to ${date} ${time}`,appointmentId:id});}return updated;}
export function addPrescription(id:string,text:string){const updated=updateBooking(id,{prescription:text,status:"completed"});if(updated)addNotification({audience:"user",title:"Prescription available",message:`Your prescription from ${updated.doctorName} is ready.`,appointmentId:id});return updated;}
export function addReview(id:string,rating:number,comment:string){return updateBooking(id,{review:{rating,comment,createdAt:new Date().toISOString()}});}
