'use client';
import { useEffect, useMemo, useState } from 'react';

type Role = 'guest' | 'user' | 'doctor';
type Status = 'Pending' | 'Confirmed' | 'Upcoming' | 'Completed' | 'Cancelled' | 'Missed';
type Doctor = { id:string; name:string; specialty:string; experience:number; rating:number; fee:number; hospital:string; bio:string; color:string; slots:string[] };
type Appointment = { id:string; doctorId:string; doctor:string; patient:string; date:string; time:string; type:string; status:Status; notes?:string; prescriptionId?:string };
type Prescription = { id:string; appointmentId:string; doctor:string; patient:string; diagnosis:string; medicines:{name:string; dosage:string; duration:string; instructions:string}[]; instructions:string; createdAt:string };
type Notification = { id:string; title:string; body:string; read:boolean; createdAt:string };
type AppState = { doctors:Doctor[]; appointments:Appointment[]; prescriptions:Prescription[]; notifications:Notification[]; profile:{name:string; email:string; phone:string; conditions:string; allergies:string; medications:string; insurance:string; emergency:string}; availability:string[] };

const doctorsSeed: Doctor[] = [
  { id:'d1', name:'Dr. Arjun Rao', specialty:'Cardiology', experience:12, rating:4.9, fee:850, hospital:'Metro Heart Institute', bio:'Preventive and clinical cardiology with patient-first care.', color:'#2f7df6', slots:['09:00 AM','10:30 AM','02:00 PM','04:30 PM'] },
  { id:'d2', name:'Dr. Maya Sharma', specialty:'Dermatology', experience:9, rating:4.8, fee:700, hospital:'CarePlus Clinic', bio:'Skin, hair and preventive dermatology consultations.', color:'#a855f7', slots:['09:30 AM','11:00 AM','01:30 PM','05:00 PM'] },
  { id:'d3', name:'Dr. Rohan Mehta', specialty:'Orthopedics', experience:14, rating:4.9, fee:900, hospital:'Motion & Bone Center', bio:'Sports injuries, joints and mobility recovery.', color:'#f97316', slots:['08:30 AM','10:00 AM','03:00 PM','05:30 PM'] },
  { id:'d4', name:'Dr. Elena Morgan', specialty:'Pediatrics', experience:8, rating:4.9, fee:750, hospital:'Little Steps Hospital', bio:'Family-focused pediatric consultations and follow-up.', color:'#14b8a6', slots:['10:00 AM','12:00 PM','03:30 PM','04:30 PM'] }
];
const initialState: AppState = {
 doctors: doctorsSeed,
 appointments: [
  {id:'a1',doctorId:'d1',doctor:'Dr. Arjun Rao',patient:'Alex Johnson',date:'2026-09-10',time:'10:30 AM',type:'Consultation',status:'Confirmed',notes:'Routine follow-up'},
  {id:'a2',doctorId:'d2',doctor:'Dr. Maya Sharma',patient:'Alex Johnson',date:'2026-08-20',time:'11:00 AM',type:'Follow-up',status:'Completed',notes:'Skin follow-up',prescriptionId:'p1'},
  {id:'a3',doctorId:'d3',doctor:'Dr. Rohan Mehta',patient:'Alex Johnson',date:'2026-09-13',time:'03:00 PM',type:'Consultation',status:'Pending'}
 ],
 prescriptions:[{id:'p1',appointmentId:'a2',doctor:'Dr. Maya Sharma',patient:'Alex Johnson',diagnosis:'Mild dermatitis',medicines:[{name:'Moisturizing cream',dosage:'Apply twice daily',duration:'14 days',instructions:'Apply on clean, dry skin'},{name:'Antihistamine',dosage:'As advised',duration:'5 days',instructions:'Use only as directed by clinician'}],instructions:'Avoid known irritants and attend follow-up if symptoms persist.',createdAt:'2026-08-20'}],
 notifications:[{id:'n1',title:'Appointment confirmed',body:'Your consultation with Dr. Arjun Rao is confirmed.',read:false,createdAt:'Today'},{id:'n2',title:'Prescription available',body:'Your completed appointment prescription is ready to view.',read:false,createdAt:'Yesterday'}],
 profile:{name:'Alex Johnson',email:'patient@schedula.demo',phone:'+91 98765 43210',conditions:'None recorded',allergies:'No known allergies',medications:'None',insurance:'Schedula Demo Health',emergency:'Sam Johnson · +91 98765 00000'},
 availability:['2026-09-10 09:00 AM','2026-09-10 10:30 AM','2026-09-10 02:00 PM','2026-09-11 09:00 AM','2026-09-11 11:00 AM']
};
const statusClass: Record<Status,string> = {Pending:'pending',Confirmed:'confirmed',Upcoming:'upcoming',Completed:'completed',Cancelled:'cancelled',Missed:'missed'};
const uid = (p:string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

export default function SchedulaApp() {
 const [state,setState] = useState<AppState>(initialState); const [role,setRole] = useState<Role>('guest'); const [page,setPage] = useState('home'); const [menu,setMenu] = useState(false); const [toast,setToast] = useState(''); const [selectedDoctor,setSelectedDoctor] = useState<Doctor | null>(null); const [selectedDate,setSelectedDate] = useState('2026-09-10'); const [selectedTime,setSelectedTime] = useState(''); const [search,setSearch] = useState(''); const [filter,setFilter] = useState('All'); const [aiOpen,setAiOpen] = useState(false); const [aiMessages,setAiMessages] = useState<{from:'user'|'ai';text:string}[]>([{from:'ai',text:'Hi! I’m Schedula AI Care Assistant. I can help you find the right specialist, understand your appointments, and answer general health questions.'}]); const [aiText,setAiText] = useState(''); const [aiLoading,setAiLoading] = useState(false);
 useEffect(()=>{ const raw=localStorage.getItem('schedula-final-state'); if(raw) try{setState(JSON.parse(raw));}catch{} },[]);
 useEffect(()=>{ if(role==='guest') return; localStorage.setItem('schedula-final-state',JSON.stringify(state)); const t=setTimeout(()=>fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})}).catch(()=>{}),500); return()=>clearTimeout(t); },[state,role]);
 const notify=(title:string,body:string)=>{setState(s=>({...s,notifications:[{id:uid('n'),title,body,read:false,createdAt:'Just now'},...s.notifications]})); setToast(title); setTimeout(()=>setToast(''),2200)};
 const login=(next:Role)=>{setRole(next);setPage(next==='doctor'?'doctor-dashboard':'doctors');notify('Welcome to Schedula',next==='doctor'?'Doctor workspace is ready.':'Your healthcare dashboard is ready.');};
 const logout=()=>{setRole('guest');setPage('home');setMenu(false);};
 const dates=['2026-09-10','2026-09-11','2026-09-12','2026-09-13','2026-09-14'];
 const filteredDoctors=useMemo(()=>state.doctors.filter(d=>(d.name+d.specialty).toLowerCase().includes(search.toLowerCase())),[state.doctors,search]);
 const userAppointments=useMemo(()=>state.appointments.filter(a=>a.patient==='Alex Johnson'),[state.appointments]);
 const changeStatus=(id:string,status:Status)=>{setState(s=>({...s,appointments:s.appointments.map(a=>a.id===id?{...a,status}:a)}));notify(`Appointment ${status.toLowerCase()}`,'Your appointment details and notifications were updated.');};
 const book=()=>{ if(!selectedDoctor||!selectedTime){setToast('Please choose a time slot');return;} const a:Appointment={id:uid('a'),doctorId:selectedDoctor.id,doctor:selectedDoctor.name,patient:'Alex Johnson',date:selectedDate,time:selectedTime,type:'Consultation',status:'Pending'}; setState(s=>({...s,appointments:[a,...s.appointments]})); notify('Booking created',`Your request with ${selectedDoctor.name} is pending confirmation.`);setPage('appointments');setSelectedTime('');};
 const addAvailability=()=>{const value=`2026-09-${10+Math.floor(Math.random()*10)} ${['09:00 AM','11:00 AM','02:00 PM','04:00 PM'][Math.floor(Math.random()*4)]}`;setState(s=>({...s,availability:[...s.availability,value]}));notify('Availability added',value);};
 const createPrescription=(a:Appointment)=>{const existing=state.prescriptions.find(p=>p.appointmentId===a.id); if(existing){setPage('prescriptions');return;} const p:Prescription={id:uid('p'),appointmentId:a.id,doctor:a.doctor,patient:a.patient,diagnosis:'Follow-up assessment',medicines:[{name:'Medication / care item',dosage:'As prescribed',duration:'7 days',instructions:'Follow clinician instructions'}],instructions:'Continue recommended care and book a follow-up if needed.',createdAt:new Date().toISOString().slice(0,10)};setState(s=>({...s,prescriptions:[p,...s.prescriptions],appointments:s.appointments.map(x=>x.id===a.id?{...x,prescriptionId:p.id,status:'Completed'}:x)}));notify('Prescription created','The user can now view and download the prescription.');};
 const downloadPdf=async(p:Prescription)=>{const { jsPDF } = await import('jspdf'); const doc=new jsPDF(); doc.setFontSize(22);doc.text('Schedula Prescription',20,20);doc.setFontSize(11);doc.text(`Doctor: ${p.doctor}`,20,35);doc.text(`Patient: ${p.patient}`,20,42);doc.text(`Date: ${p.createdAt}`,20,49);doc.text(`Diagnosis: ${p.diagnosis}`,20,60);let y=75;p.medicines.forEach((m,i)=>{doc.text(`${i+1}. ${m.name} — ${m.dosage} — ${m.duration}`,20,y);y+=8;doc.text(m.instructions,25,y);y+=10;});doc.text(`Instructions: ${p.instructions}`,20,y+8);doc.save(`schedula-prescription-${p.id}.pdf`);};
 const sendAI=async()=>{const message=aiText.trim();if(!message)return;setAiMessages(m=>[...m,{from:'user',text:message}]);setAiText('');setAiLoading(true);try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,doctors:state.doctors.map(d=>({name:d.name,specialty:d.specialty}))})});const data=await r.json();setAiMessages(m=>[...m,{from:'ai',text:data.reply||data.error||'Please try again.'}]);}catch{setAiMessages(m=>[...m,{from:'ai',text:'I could not reach the assistant. Please try again.'}]);}finally{setAiLoading(false)}};
 const nav=(target:string)=>{setPage(target);setMenu(false)};
 if(role==='guest') return <Landing login={login} />;
 return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brand"><span>✚</span><b>Schedula</b></div><p className="role-label">{role==='doctor'?'DOCTOR PORTAL':'PATIENT PORTAL'}</p><nav>{(role==='doctor'?[['doctor-dashboard','◈','Dashboard'],['doctor-calendar','▦','Calendar'],['doctor-appointments','▤','Appointments'],['doctor-profile','♙','Profile'],['doctor-prescriptions','▣','Prescriptions']]:[['doctors','⌕','Find Doctors'],['appointments','▤','My Appointments'],['prescriptions','▣','Prescriptions'],['profile','♙','My Profile'],['notifications','◌','Notifications']]).map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>nav(id)}><span>{icon}</span>{label}</button>)}</nav><div className="side-bottom"><button onClick={()=>setAiOpen(true)}>✦ AI Care Assistant</button><button onClick={logout}>⇥ Sign out</button></div></aside><main className="main"><header className="top"><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button><div><small>Healthcare, simplified</small><h3>{page.replace('doctor-','').replaceAll('-',' ')}</h3></div><div className="top-actions"><button className="icon-btn" onClick={()=>nav('notifications')}>◌<i>{state.notifications.filter(n=>!n.read).length}</i></button><button className="ai-button" onClick={()=>setAiOpen(true)}>✦ Ask Care AI</button><div className="avatar">{role==='doctor'?'DR':'AJ'}</div></div></header>
 {role==='user'?<UserPages/>:<DoctorPages/>}
 </main>{toast&&<div className="toast">✓ {toast}</div>}{aiOpen&&<div className="ai-panel"><div className="ai-head"><div><b>✦ Schedula AI Care</b><small>General health & appointment guidance</small></div><button onClick={()=>setAiOpen(false)}>×</button></div><div className="ai-chat">{aiMessages.map((m,i)=><div key={i} className={`bubble ${m.from}`}>{m.text}</div>)}{aiLoading&&<div className="bubble ai">Thinking…</div>}</div><div className="ai-input"><input value={aiText} onChange={e=>setAiText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendAI()} placeholder="Ask about care or appointments…"/><button onClick={sendAI}>Send</button></div><p className="ai-safe">Not for emergencies or diagnosis. Contact a clinician for medical decisions.</p></div>}</div>;

 function UserPages(){
  if(page==='doctors') return <section className="page"><div className="hero"><div><span className="eyebrow">FIND THE RIGHT CARE</span><h1>Care that fits your life.</h1><p>Search trusted specialists, compare availability and book in a few simple steps.</p></div><div className="hero-stat"><b>24/7</b><span>Smart appointment support</span></div></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search doctor or specialty"/><button onClick={()=>setSearch('')}>Clear</button></div><div className="doctor-grid">{filteredDoctors.map(d=><article className="doctor-card" key={d.id}><div className="doctor-avatar" style={{background:d.color}}>{d.name.split(' ').slice(1).map(x=>x[0]).join('')}</div><div><div className="card-row"><span className="pill">{d.specialty}</span><span>★ {d.rating}</span></div><h3>{d.name}</h3><p>{d.hospital}</p><div className="meta"><span>{d.experience} yrs exp.</span><b>₹{d.fee}</b></div><button className="primary full" onClick={()=>{setSelectedDoctor(d);setPage('booking')}}>View & Book</button></div></article>)}</div></section>;
  if(page==='booking') return <section className="page"><button className="back" onClick={()=>setPage('doctors')}>← Back to doctors</button><div className="booking-layout"><div><span className="eyebrow">BOOK APPOINTMENT</span><h1>{selectedDoctor?.name||'Choose a doctor'}</h1><p>{selectedDoctor?.specialty} · {selectedDoctor?.hospital}</p><div className="steps"><span>1 Doctor</span><span className="active">2 Date & time</span><span>3 Confirm</span></div><div className="section-card"><h3>Select date</h3><div className="date-grid">{dates.map(d=><button key={d} onClick={()=>setSelectedDate(d)} className={selectedDate===d?'selected':''}><b>{new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short'})}</b><strong>{d.slice(-2)}</strong><small>{new Date(d+'T12:00:00').toLocaleDateString('en',{month:'short'})}</small></button>)}</div><h3>Available times</h3><div className="slot-grid">{(selectedDoctor?.slots||[]).map(t=><button key={t} className={selectedTime===t?'selected':''} onClick={()=>setSelectedTime(t)}>{t}</button>)}</div></div></div><aside className="summary"><span className="eyebrow">BOOKING SUMMARY</span><h3>{selectedDoctor?.name}</h3><p>{selectedDate} · {selectedTime||'Choose time'}</p><p>Consultation fee <b>₹{selectedDoctor?.fee||0}</b></p><button className="primary full" onClick={book}>Confirm appointment</button></aside></div></section>;
  if(page==='appointments') return <section className="page"><div className="page-title"><div><span className="eyebrow">YOUR CARE TIMELINE</span><h1>My appointments</h1></div><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Pending','Confirmed','Upcoming','Completed','Cancelled','Missed'].map(x=><option key={x}>{x}</option>)}</select></div><div className="appointment-list">{userAppointments.filter(a=>filter==='All'||a.status===filter).map(a=><AppointmentCard key={a.id} a={a} doctor={false}/>)}</div></section>;
  if(page==='prescriptions') return <section className="page"><div className="page-title"><div><span className="eyebrow">DAY 6 FEATURE</span><h1>My prescriptions</h1><p>View prescriptions from completed appointments and download a PDF copy.</p></div></div><div className="prescription-grid">{state.prescriptions.map(p=><article className="prescription-card" key={p.id}><div className="rx">Rx</div><span>{p.createdAt}</span><h3>{p.diagnosis}</h3><p>{p.doctor}</p><ul>{p.medicines.map((m,i)=><li key={i}><b>{m.name}</b><small>{m.dosage} · {m.duration}</small></li>)}</ul><div className="card-actions"><button onClick={()=>downloadPdf(p)}>⇩ Download PDF</button><button onClick={()=>alert(p.instructions)}>View details</button></div></article>)}</div></section>;
  if(page==='profile') return <ProfilePage/>;
  if(page==='notifications') return <section className="page"><div className="page-title"><div><span className="eyebrow">STAY UPDATED</span><h1>Notifications</h1></div><button onClick={()=>setState(s=>({...s,notifications:s.notifications.map(n=>({...n,read:true}))}))}>Mark all read</button></div><div className="notification-list">{state.notifications.map(n=><article className={n.read?'notification read':'notification'} key={n.id}><div className="notice-icon">◌</div><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.createdAt}</small></div></article>)}</div></section>;
  return null;
 }
 function DoctorPages(){
  const all=state.appointments;
  if(page==='doctor-dashboard') return <section className="page"><div className="page-title"><div><span className="eyebrow">DOCTOR WORKSPACE</span><h1>Good morning, Doctor.</h1><p>Here is a focused view of your upcoming care schedule.</p></div><button className="primary" onClick={()=>nav('doctor-appointments')}>View all appointments</button></div><div className="stats"><Stat label="Upcoming" value={all.filter(a=>['Pending','Confirmed','Upcoming'].includes(a.status)).length}/><Stat label="Completed" value={all.filter(a=>a.status==='Completed').length}/><Stat label="Available slots" value={state.availability.length}/><Stat label="Patient satisfaction" value="4.9/5"/></div><div className="two-col"><section className="panel"><div className="panel-head"><h2>Upcoming appointments</h2><button onClick={()=>nav('doctor-calendar')}>Calendar</button></div>{all.filter(a=>['Pending','Confirmed','Upcoming'].includes(a.status)).slice(0,4).map(a=><AppointmentCard key={a.id} a={a} doctor/> )}</section><section className="panel"><div className="panel-head"><h2>Quick actions</h2></div><button className="quick" onClick={()=>nav('doctor-profile')}>♙ Update profile & availability</button><button className="quick" onClick={()=>nav('doctor-prescriptions')}>▣ Manage prescriptions</button><button className="quick" onClick={addAvailability}>＋ Add an available slot</button></section></div></section>;
  if(page==='doctor-calendar') return <section className="page"><div className="page-title"><div><span className="eyebrow">DAY / WEEK / MONTH</span><h1>Appointment calendar</h1></div><button className="primary" onClick={addAvailability}>＋ Add availability</button></div><div className="calendar"><div className="calendar-head">{dates.map(d=><b key={d}>{new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short',day:'numeric'})}</b>)}</div><div className="calendar-body">{dates.map(d=><div className="day-col" key={d}>{state.availability.filter(x=>x.startsWith(d)).map((x,i)=><button className="availability" key={i}>{x.split(' ')[1]} {x.split(' ')[2]}</button>)}{all.filter(a=>a.date===d).map(a=><button className={`cal-appt ${statusClass[a.status]}`} key={a.id} onClick={()=>changeStatus(a.id,a.status==='Pending'?'Confirmed':a.status)}><b>{a.time}</b><span>{a.patient}</span><small>{a.status}</small></button>)}</div>)}</div></div><p className="muted">Demo interaction: click a pending calendar appointment to confirm it. Completed, cancelled and missed items remain status-controlled.</p></section>;
  if(page==='doctor-appointments') return <section className="page"><div className="page-title"><div><span className="eyebrow">MANAGE PATIENT CARE</span><h1>All appointments</h1></div><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Pending','Confirmed','Upcoming','Completed','Cancelled','Missed'].map(x=><option key={x}>{x}</option>)}</select></div><div className="appointment-list">{all.filter(a=>filter==='All'||a.status===filter).map(a=><AppointmentCard key={a.id} a={a} doctor/>)}</div></section>;
  if(page==='doctor-prescriptions') return <section className="page"><div className="page-title"><div><span className="eyebrow">PRESCRIPTION MANAGEMENT</span><h1>Create & manage prescriptions</h1></div></div><div className="two-col"><section className="panel"><h2>Completed appointments</h2>{all.filter(a=>a.status==='Completed').map(a=><div className="row-item" key={a.id}><div><b>{a.patient}</b><small>{a.date} · {a.type}</small></div><button onClick={()=>createPrescription(a)}>{a.prescriptionId?'View prescription':'Create prescription'}</button></div>)}</section><section className="panel"><h2>Existing prescriptions</h2>{state.prescriptions.map(p=><div className="row-item" key={p.id}><div><b>{p.patient}</b><small>{p.diagnosis}</small></div><button onClick={()=>downloadPdf(p)}>PDF</button></div>)}</section></div></section>;
  if(page==='doctor-profile') return <section className="page"><div className="page-title"><div><span className="eyebrow">DOCTOR PROFILE</span><h1>Profile & availability</h1><p>Manage professional information and reusable appointment slots.</p></div><button className="primary" onClick={addAvailability}>＋ Add slot</button></div><div className="two-col"><section className="panel"><h2>Professional profile</h2><div className="form-grid"><label>Display name<input defaultValue="Dr. Arjun Rao"/></label><label>Specialty<input defaultValue="Cardiology"/></label><label>Experience<input defaultValue="12 years"/></label><label>Hospital<input defaultValue="Metro Heart Institute"/></label></div><button className="primary" onClick={()=>notify('Profile saved','Doctor profile information was updated.')}>Save profile</button></section><section className="panel"><h2>Recurring availability</h2><p className="muted">Current reusable slots are visible to patients during booking.</p>{state.availability.map((x,i)=><div className="slot-row" key={i}><span>{x}</span><button onClick={()=>setState(s=>({...s,availability:s.availability.filter((_,idx)=>idx!==i)}))}>Remove</button></div>)}</section></div></section>;
  return null;
 }
 function AppointmentCard({a,doctor}:{a:Appointment;doctor:boolean}){const prescription=state.prescriptions.find(p=>p.appointmentId===a.id);return <article className="appointment-card"><div className="appt-date"><b>{a.date.slice(-2)}</b><span>{new Date(a.date+'T12:00:00').toLocaleDateString('en',{month:'short'})}</span></div><div className="appt-main"><div className="card-row"><h3>{doctor?a.patient:a.doctor}</h3><span className={`status ${statusClass[a.status]}`}>{a.status}</span></div><p>{a.type} · {a.time} {a.notes&&`· ${a.notes}`}</p><small>{doctor?'👤 Patient details available':'🩺 Doctor appointment'}</small></div><div className="appt-actions">{doctor&&a.status==='Pending'&&<><button onClick={()=>changeStatus(a.id,'Confirmed')}>Confirm</button><button onClick={()=>changeStatus(a.id,'Cancelled')}>Decline</button></>}{doctor&&['Confirmed','Upcoming'].includes(a.status)&&<><button onClick={()=>changeStatus(a.id,'Completed')}>Complete</button><button onClick={()=>changeStatus(a.id,'Cancelled')}>Cancel</button></>}{doctor&&a.status==='Completed'&&<button onClick={()=>createPrescription(a)}>{prescription?'Prescription':'Create Rx'}</button>}{!doctor&&a.status==='Completed'&&<>{prescription?<button onClick={()=>downloadPdf(prescription)}>Download PDF</button>:<span className="muted">Prescription not available</span>}<button onClick={()=>{setSelectedDoctor(state.doctors.find(d=>d.id===a.doctorId)||null);setPage('booking')}}>Rebook</button></>}</div></article>}
 function ProfilePage(){const [draft,setDraft]=useState(state.profile);return <section className="page"><div className="page-title"><div><span className="eyebrow">YOUR HEALTH PROFILE</span><h1>Personal & care information</h1></div><button className="primary" onClick={()=>{setState(s=>({...s,profile:draft}));notify('Profile updated','Your information was saved.')}}>Save changes</button></div><div className="stats"><Stat label="Total prescriptions" value={state.prescriptions.length}/><Stat label="Completed appointments" value={userAppointments.filter(a=>a.status==='Completed').length}/><Stat label="Test reports" value="0"/><Stat label="Profile completion" value="92%"/></div><div className="form-grid profile-form">{Object.entries(draft).map(([key,val])=><label key={key}>{key.replace(/([A-Z])/g,' $1')}<input value={val} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div></section>}
}
function Landing({login}:{login:(r:Role)=>void}){const [mode,setMode]=useState<'user'|'doctor'>('user');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!email.includes('@')||password.length<4){setError('Enter a valid email and a password of at least 4 characters.');return;}login(mode)};return <div className="landing"><section className="landing-left"><div className="brand"><span>✚</span><b>Schedula</b></div><div className="landing-copy"><span className="eyebrow light">SMART HEALTHCARE PLATFORM</span><h1>Better care starts with better scheduling.</h1><p>One polished workspace for patients and doctors — appointments, availability, prescriptions, notifications and intelligent care guidance.</p><div className="feature-points"><span>✓ Book in minutes</span><span>✓ Manage complete care</span><span>✓ Secure demo persistence</span></div></div><div className="mini-card">This final build combines all Day 1–6 requirements into one responsive experience.</div></section><section className="login-pane"><div className="login-card"><div className="mode-switch"><button className={mode==='user'?'selected':''} onClick={()=>setMode('user')}>Patient</button><button className={mode==='doctor'?'selected':''} onClick={()=>setMode('doctor')}>Doctor</button></div><span className="eyebrow">WELCOME BACK</span><h2>{mode==='user'?'Your care, organized.':'Your clinic, in control.'}</h2><p>Use any valid email and a password of 4+ characters. Demo credentials are shown below.</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={mode==='user'?'patient@schedula.demo':'doctor@schedula.demo'}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="demo123"/></label><button className="primary full" type="submit">Continue to {mode==='user'?'Patient':'Doctor'} Portal →</button></form><div className="demo-creds">Demo: <b>{mode==='user'?'patient@schedula.demo':'doctor@schedula.demo'}</b> · <b>demo123</b></div></div></section></div>}
function Stat({label,value}:{label:string;value:string|number}){return <article className="stat"><span>{label}</span><b>{value}</b><small>Updated now</small></article>}
