"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { isDoctorIdentifierTaken, registerDoctor } from "@/features/doctor-portal/storage";
import type { DoctorProfile } from "@/features/doctor-portal/types";

const initial = { firstName:"", lastName:"", dateOfBirth:"", gender:"", specialty:"General Medicine", licenseNumber:"", experienceYears:"", consultationFee:"", phone:"", email:"", clinicName:"", clinicAddress:"", username:"", password:"", confirmPassword:"", bio:"" };
type FormState = typeof initial;

export default function DoctorRegisterPage() {
  const router = useRouter(); const [form, setForm] = useState<FormState>(initial); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const set = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError("");
    const required: (keyof FormState)[] = ["firstName","lastName","dateOfBirth","specialty","licenseNumber","experienceYears","consultationFee","phone","email","clinicName","username","password","confirmPassword"];
    if (required.some((key) => !form[key].trim())) return setError("Please complete all required fields.");
    if (!/^\S+@\S+\.\S+$/.test(form.email)) return setError("Enter a valid email address.");
    if (!/^[0-9+()\-\s]{7,20}$/.test(form.phone)) return setError("Enter a valid contact number.");
    if (Number(form.experienceYears) < 0 || Number(form.experienceYears) > 60) return setError("Enter valid years of experience.");
    if (Number(form.consultationFee) < 0) return setError("Consultation fee cannot be negative.");
    if (form.username.trim().length < 3) return setError("Username must contain at least 3 characters.");
    if (form.password.length < 6) return setError("Password must contain at least 6 characters.");
    if (form.password !== form.confirmPassword) return setError("Password and confirm password do not match.");
    if (isDoctorIdentifierTaken(form.email, form.username)) return setError("An account already exists with this email or username.");
    setSubmitting(true);
    const profile: DoctorProfile = { id: `doctor-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, firstName: form.firstName.trim(), lastName: form.lastName.trim(), dateOfBirth: form.dateOfBirth, gender: form.gender, specialty: form.specialty, licenseNumber: form.licenseNumber.trim(), experienceYears: Number(form.experienceYears), consultationFee: Number(form.consultationFee), phone: form.phone.trim(), email: form.email.trim(), clinicName: form.clinicName.trim(), clinicAddress: form.clinicAddress.trim(), username: form.username.trim(), password: form.password, bio: form.bio.trim() || `Experienced ${form.specialty} professional providing patient-focused care.`, createdAt: new Date().toISOString() };
    registerDoctor(profile); setTimeout(() => router.push("/doctor/login?registered=1"), 250);
  };
  const field = (label: string, key: keyof FormState, type = "text", required = true, placeholder?: string) => <label className="block text-sm font-semibold">{label}{required ? <span className="text-red-600"> *</span> : null}<input value={form[key]} onChange={(e) => set(key, e.target.value)} type={type} placeholder={placeholder} className="mt-1.5 h-11 w-full rounded-xl border border-[var(--line)] bg-white px-3 text-sm outline-none placeholder:text-stone-400 focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></label>;
  return <main className="min-h-screen bg-[var(--canvas)] px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto max-w-5xl"><div className="mb-7 flex items-center justify-between"><Link href="/doctor/login" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--brand)] font-bold text-white">S</span><span><span className="block font-bold">Schedula</span><span className="text-xs text-[var(--muted)]">Doctor portal</span></span></Link><Link href="/login" className="text-sm font-semibold text-[var(--brand)] hover:underline">User portal →</Link></div>
    <section className="overflow-hidden rounded-3xl border border-[var(--line)] bg-white shadow-[0_24px_80px_rgba(27,41,37,0.08)]"><div className="bg-[var(--brand-deep)] px-6 py-8 text-white sm:px-10"><p className="text-sm font-semibold text-emerald-200">Join the care network</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Create your doctor account.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-50/80">Set up your professional profile once, then manage availability and appointments from your dedicated workspace.</p></div>
    <form onSubmit={submit} className="p-5 sm:p-8 lg:p-10" noValidate>{error ? <p role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-800">{error}</p> : null}
      <div className="grid gap-8"><fieldset><legend className="text-lg font-bold">Personal details</legend><p className="mt-1 text-sm text-[var(--muted)]">Basic information used to identify you professionally.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("First name","firstName")} {field("Last name","lastName")} {field("Date of birth","dateOfBirth","date")}<label className="block text-sm font-semibold">Gender <span className="text-[var(--muted)]">(optional)</span><select value={form.gender} onChange={(e)=>set("gender",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[var(--line)] bg-white px-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100"><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer to self-describe</option></select></label></div></fieldset>
      <fieldset className="border-t border-[var(--line)] pt-8"><legend className="text-lg font-bold">Professional details</legend><p className="mt-1 text-sm text-[var(--muted)]">These details power your public doctor profile.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Specialty <span className="text-red-600">*</span><select value={form.specialty} onChange={(e)=>set("specialty",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[var(--line)] bg-white px-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100">{["General Medicine","Dermatology","Cardiology","Orthopedics","Pediatrics","Neurology","Gynecology","Psychiatry"].map((x)=><option key={x}>{x}</option>)}</select></label>{field("Medical license number","licenseNumber","text",true,"e.g. MED-12345")}{field("Years of experience","experienceYears","number",true,"e.g. 8")}{field("Consultation fee (₹)","consultationFee","number",true,"e.g. 800")}</div><label className="mt-4 block text-sm font-semibold">Professional bio <span className="text-[var(--muted)]">(optional)</span><textarea value={form.bio} onChange={(e)=>set("bio",e.target.value)} rows={3} placeholder="Tell patients a little about your expertise and care approach." className="mt-1.5 w-full rounded-xl border border-[var(--line)] px-3 py-3 text-sm outline-none placeholder:text-stone-400 focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></label></fieldset>
      <fieldset className="border-t border-[var(--line)] pt-8"><legend className="text-lg font-bold">Contact & clinic</legend><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("Email address","email","email",true,"doctor@clinic.com")} {field("Phone number","phone","tel",true,"+91 98765 43210")} {field("Clinic / hospital name","clinicName", "text")} {field("Clinic address","clinicAddress","text",false,"Optional")}</div></fieldset>
      <fieldset className="border-t border-[var(--line)] pt-8"><legend className="text-lg font-bold">Account security</legend><div className="mt-5 grid gap-4 sm:grid-cols-2">{field("Username","username","text",true,"Choose a username")} {field("Password","password","password",true,"Minimum 6 characters")} {field("Confirm password","confirmPassword","password",true,"Re-enter password")}</div></fieldset></div>
      <div className="mt-8 flex flex-col-reverse gap-3 border-t border-[var(--line)] pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-[var(--muted)]">Already registered? <Link href="/doctor/login" className="font-bold text-[var(--brand)]">Sign in</Link></p><button disabled={submitting} className="rounded-xl bg-[var(--brand)] px-6 py-3 text-sm font-bold text-white hover:bg-[var(--brand-deep)] disabled:opacity-50">{submitting ? "Creating account…" : "Create doctor account →"}</button></div>
    </form></section></div></main>;
}
